# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/abartfeld/test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/abartfeld/test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/abartfeld/test/CMakeFiles /home/abartfeld/test//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/abartfeld/test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gpx_viewer

# Build rule for target.
gpx_viewer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gpx_viewer
.PHONY : gpx_viewer

# fast build rule for target.
gpx_viewer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpx_viewer.dir/build.make CMakeFiles/gpx_viewer.dir/build
.PHONY : gpx_viewer/fast

#=============================================================================
# Target rules for targets named gpx_viewer_autogen_timestamp_deps

# Build rule for target.
gpx_viewer_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gpx_viewer_autogen_timestamp_deps
.PHONY : gpx_viewer_autogen_timestamp_deps

# fast build rule for target.
gpx_viewer_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpx_viewer_autogen_timestamp_deps.dir/build.make CMakeFiles/gpx_viewer_autogen_timestamp_deps.dir/build
.PHONY : gpx_viewer_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named gpx_viewer_autogen

# Build rule for target.
gpx_viewer_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gpx_viewer_autogen
.PHONY : gpx_viewer_autogen

# fast build rule for target.
gpx_viewer_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpx_viewer_autogen.dir/build.make CMakeFiles/gpx_viewer_autogen.dir/build
.PHONY : gpx_viewer_autogen/fast

MapWidget.o: MapWidget.cpp.o
.PHONY : MapWidget.o

# target to build an object file
MapWidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpx_viewer.dir/build.make CMakeFiles/gpx_viewer.dir/MapWidget.cpp.o
.PHONY : MapWidget.cpp.o

MapWidget.i: MapWidget.cpp.i
.PHONY : MapWidget.i

# target to preprocess a source file
MapWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpx_viewer.dir/build.make CMakeFiles/gpx_viewer.dir/MapWidget.cpp.i
.PHONY : MapWidget.cpp.i

MapWidget.s: MapWidget.cpp.s
.PHONY : MapWidget.s

# target to generate assembly for a file
MapWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpx_viewer.dir/build.make CMakeFiles/gpx_viewer.dir/MapWidget.cpp.s
.PHONY : MapWidget.cpp.s

gpx_viewer_autogen/mocs_compilation.o: gpx_viewer_autogen/mocs_compilation.cpp.o
.PHONY : gpx_viewer_autogen/mocs_compilation.o

# target to build an object file
gpx_viewer_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpx_viewer.dir/build.make CMakeFiles/gpx_viewer.dir/gpx_viewer_autogen/mocs_compilation.cpp.o
.PHONY : gpx_viewer_autogen/mocs_compilation.cpp.o

gpx_viewer_autogen/mocs_compilation.i: gpx_viewer_autogen/mocs_compilation.cpp.i
.PHONY : gpx_viewer_autogen/mocs_compilation.i

# target to preprocess a source file
gpx_viewer_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpx_viewer.dir/build.make CMakeFiles/gpx_viewer.dir/gpx_viewer_autogen/mocs_compilation.cpp.i
.PHONY : gpx_viewer_autogen/mocs_compilation.cpp.i

gpx_viewer_autogen/mocs_compilation.s: gpx_viewer_autogen/mocs_compilation.cpp.s
.PHONY : gpx_viewer_autogen/mocs_compilation.s

# target to generate assembly for a file
gpx_viewer_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpx_viewer.dir/build.make CMakeFiles/gpx_viewer.dir/gpx_viewer_autogen/mocs_compilation.cpp.s
.PHONY : gpx_viewer_autogen/mocs_compilation.cpp.s

gpxparser.o: gpxparser.cpp.o
.PHONY : gpxparser.o

# target to build an object file
gpxparser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpx_viewer.dir/build.make CMakeFiles/gpx_viewer.dir/gpxparser.cpp.o
.PHONY : gpxparser.cpp.o

gpxparser.i: gpxparser.cpp.i
.PHONY : gpxparser.i

# target to preprocess a source file
gpxparser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpx_viewer.dir/build.make CMakeFiles/gpx_viewer.dir/gpxparser.cpp.i
.PHONY : gpxparser.cpp.i

gpxparser.s: gpxparser.cpp.s
.PHONY : gpxparser.s

# target to generate assembly for a file
gpxparser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpx_viewer.dir/build.make CMakeFiles/gpx_viewer.dir/gpxparser.cpp.s
.PHONY : gpxparser.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpx_viewer.dir/build.make CMakeFiles/gpx_viewer.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpx_viewer.dir/build.make CMakeFiles/gpx_viewer.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpx_viewer.dir/build.make CMakeFiles/gpx_viewer.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o
.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpx_viewer.dir/build.make CMakeFiles/gpx_viewer.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i
.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpx_viewer.dir/build.make CMakeFiles/gpx_viewer.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s
.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpx_viewer.dir/build.make CMakeFiles/gpx_viewer.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

qcustomplot.o: qcustomplot.cpp.o
.PHONY : qcustomplot.o

# target to build an object file
qcustomplot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpx_viewer.dir/build.make CMakeFiles/gpx_viewer.dir/qcustomplot.cpp.o
.PHONY : qcustomplot.cpp.o

qcustomplot.i: qcustomplot.cpp.i
.PHONY : qcustomplot.i

# target to preprocess a source file
qcustomplot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpx_viewer.dir/build.make CMakeFiles/gpx_viewer.dir/qcustomplot.cpp.i
.PHONY : qcustomplot.cpp.i

qcustomplot.s: qcustomplot.cpp.s
.PHONY : qcustomplot.s

# target to generate assembly for a file
qcustomplot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpx_viewer.dir/build.make CMakeFiles/gpx_viewer.dir/qcustomplot.cpp.s
.PHONY : qcustomplot.cpp.s

qrc_resources.o: qrc_resources.cpp.o
.PHONY : qrc_resources.o

# target to build an object file
qrc_resources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpx_viewer.dir/build.make CMakeFiles/gpx_viewer.dir/qrc_resources.cpp.o
.PHONY : qrc_resources.cpp.o

qrc_resources.i: qrc_resources.cpp.i
.PHONY : qrc_resources.i

# target to preprocess a source file
qrc_resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpx_viewer.dir/build.make CMakeFiles/gpx_viewer.dir/qrc_resources.cpp.i
.PHONY : qrc_resources.cpp.i

qrc_resources.s: qrc_resources.cpp.s
.PHONY : qrc_resources.s

# target to generate assembly for a file
qrc_resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpx_viewer.dir/build.make CMakeFiles/gpx_viewer.dir/qrc_resources.cpp.s
.PHONY : qrc_resources.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... gpx_viewer_autogen"
	@echo "... gpx_viewer_autogen_timestamp_deps"
	@echo "... gpx_viewer"
	@echo "... MapWidget.o"
	@echo "... MapWidget.i"
	@echo "... MapWidget.s"
	@echo "... gpx_viewer_autogen/mocs_compilation.o"
	@echo "... gpx_viewer_autogen/mocs_compilation.i"
	@echo "... gpx_viewer_autogen/mocs_compilation.s"
	@echo "... gpxparser.o"
	@echo "... gpxparser.i"
	@echo "... gpxparser.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... qcustomplot.o"
	@echo "... qcustomplot.i"
	@echo "... qcustomplot.s"
	@echo "... qrc_resources.o"
	@echo "... qrc_resources.i"
	@echo "... qrc_resources.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

